# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0403beea9255c5914920d6ccd1d64aab5738bfa339943cfb7a1ce4a57908745867adf824cd7c0d9a2f5cc84b7e9ad10cad0eb30d2d164a91a6e2127a7834a107

test:
  secret_key_base: 0648d6be634dc59557745837d9d5fe84abff4b3768b4cbea21164d597a54e9260970b8e600ccddc68219a051e50f32ee64d125d122c8123e280b1749cf279498

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
